$Title ('DTC/PC BIOS IBMINC Include File Dummy Assembly V1.0')
$Pagelength (80) Pagewidth (132) Debug Nogen
Name IbmInc


;    Author:	  Don K. Harrison

;    Start date:  December 28, 1983	  Last edit:  December 28, 1983

;		************************
;		*  Module Description  *  
;		************************
;
;	This module is a dummy assembly of the include file used
;    by all modules.





;	  (c) Display Telecommunications Corporation, 1983
;			All Rights Reserved
$Eject


;		**********************
;		*  Revision History  *  
;		**********************







$Eject

;	Ibminc.tmp file same as IbmInc except $Nolist command commented Out
$Include (Ibminc.tmp)

End